import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'components/accordion/index': 'src/components/accordion/index.ts',
    'components/alert/index': 'src/components/alert/index.ts',
    'components/breadcrumbs/index': 'src/components/breadcrumbs/index.ts',
    'components/button/index': 'src/components/button/index.ts',
    'components/carousel/index': 'src/components/carousel/index.ts',
    'components/checkbox/index': 'src/components/checkbox/index.ts',
    'components/combobox/index': 'src/components/combobox/index.ts',
    'components/command-palette/index': 'src/components/command-palette/index.ts',
    'components/data-grid/index': 'src/components/data-grid/index.ts',
    'components/date-picker/index': 'src/components/date-picker/index.ts',
    'components/dialog/index': 'src/components/dialog/index.ts',
    'components/drawer/index': 'src/components/drawer/index.ts',
    'components/empty-state/index': 'src/components/empty-state/index.ts',
    'components/error-summary/index': 'src/components/error-summary/index.ts',
    'components/file-upload/index': 'src/components/file-upload/index.ts',
    'components/form-field/index': 'src/components/form-field/index.ts',
    'components/input/index': 'src/components/input/index.ts',
    'components/link/index': 'src/components/link/index.ts',
    'components/listbox/index': 'src/components/listbox/index.ts',
    'components/menu/index': 'src/components/menu/index.ts',
    'components/number-field/index': 'src/components/number-field/index.ts',
    'components/pagination/index': 'src/components/pagination/index.ts',
    'components/popover/index': 'src/components/popover/index.ts',
    'components/progress-bar/index': 'src/components/progress-bar/index.ts',
    'components/radio-group/index': 'src/components/radio-group/index.ts',
    'components/rich-text-editor/index': 'src/components/rich-text-editor/index.ts',
    'components/search-field/index': 'src/components/search-field/index.ts',
    'components/select/index': 'src/components/select/index.ts',
    'components/skeleton/index': 'src/components/skeleton/index.ts',
    'components/skip-link/index': 'src/components/skip-link/index.ts',
    'components/slider/index': 'src/components/slider/index.ts',
    'components/stepper/index': 'src/components/stepper/index.ts',
    'components/switch/index': 'src/components/switch/index.ts',
    'components/table/index': 'src/components/table/index.ts',
    'components/tabs/index': 'src/components/tabs/index.ts',
    'components/text/index': 'src/components/text/index.ts',
    'components/textarea/index': 'src/components/textarea/index.ts',
    'components/time-picker/index': 'src/components/time-picker/index.ts',
    'components/toast/index': 'src/components/toast/index.ts',
    'components/tooltip/index': 'src/components/tooltip/index.ts',
    'components/tree-view/index': 'src/components/tree-view/index.ts',
    'components/visually-hidden/index': 'src/components/visually-hidden/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  sourcemap: false,
  clean: true,
  treeshake: true,
  minify: true,
  external: ['react', 'react-dom'],
  esbuildOptions(options) {
    options.jsx = 'automatic';
  },
});
